// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SlidEnglish.Server;

namespace SlidEnglish.Server.Migrations
{
    [DbContext(typeof(SlidEnglishContext))]
    [Migration("20190729062524_usage-examples")]
    partial class usageexamples
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "3.0.0-preview7.19362.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("SlidEnglish.Domain.UsageExample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn);

                    b.Property<string>("Text")
                        .IsRequired();

                    b.Property<int?>("WordId");

                    b.HasKey("Id");

                    b.HasIndex("WordId");

                    b.ToTable("UsageExample");
                });

            modelBuilder.Entity("SlidEnglish.Domain.Word", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn);

                    b.Property<string>("Associations")
                        .IsRequired();

                    b.Property<string>("Text")
                        .IsRequired();

                    b.Property<int?>("WordId");

                    b.HasKey("Id");

                    b.HasIndex("WordId");

                    b.ToTable("Word");
                });

            modelBuilder.Entity("SlidEnglish.Domain.UsageExample", b =>
                {
                    b.HasOne("SlidEnglish.Domain.Word", null)
                        .WithMany("UsageExamples")
                        .HasForeignKey("WordId");
                });

            modelBuilder.Entity("SlidEnglish.Domain.Word", b =>
                {
                    b.HasOne("SlidEnglish.Domain.Word", null)
                        .WithMany("Synonyms")
                        .HasForeignKey("WordId");
                });
#pragma warning restore 612, 618
        }
    }
}
